#! /bin/sh

name=init
version=0
revision=1
skip_pkg_check=yes
hostdeps="gcc"
imagedeps="build-essential"
deps="glibc"

build() {
    "${TRIPLE}-gcc" -o init -x c -O3 - << EOF
#include <stdio.h>
#include <sys/ioctl.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
    if (getpid() != 1) {
        fprintf(stderr, "%s: PID must be 1\n", argv[0]);
        return 1;
    }

    if (setsid() == -1) {
        fprintf(stderr, "%s: setsid failed: %m\n", argv[0]);
        return 1;
    }

    if (ioctl(STDIN_FILENO, TIOCSCTTY, 0) == -1) {
        fprintf(stderr, "%s: failed to set controlling terminal: %m\n", argv[0]);
        return 1;
    }

    execl("/usr/bin/bash", "/usr/bin/bash", NULL);
    fprintf(stderr, "%s: failed to start bash: %m\n", argv[0]);
    return 1;
}
EOF
}

package() {
    install -Dm755 init "${dest_dir}/usr/bin/init"

    post_package_strip
}
