#! /bin/sh

JINX_MAJOR_VER=0.6

TRIPLE="${JINX_ARCH}"-unknown-linux-gnu

post_package_strip() {
    if [ -z "$strip_command" ]; then
        strip_command="${TRIPLE}-strip"
    fi

    for f in $(find "${dest_dir}"); do
        if file "$f" | grep 'not stripped' >/dev/null; then
            echo "* stripping '$f'..."
            stripped_file="$(mktemp)"
            ${strip_command} "$f" -o "$stripped_file"
            chmod --reference="$f" "$stripped_file"
            mv -f "$stripped_file" "$f"
        fi
    done
}

autotools_regen() {
    find . '(' -name configure.ac -o -name configure.in ')' -type f -print0 \
            | sort -z | xargs -0 autoreconf -fvi "$@"
}

autotools_configure() {
    "${source_dir}/configure"                   \
        --host="${TRIPLE}"                      \
        --prefix="${prefix}"                    \
        --sbindir="${prefix}/bin"               \
        "$@"
}

cmake_configure() {
    cmake "${source_dir}"                                                                   \
        -GNinja                                                                             \
        -DCMAKE_TOOLCHAIN_FILE="${base_dir}/build-support/cmake-toolchain-${JINX_ARCH}.txt" \
        -DCMAKE_INSTALL_PREFIX="${prefix}"                                                  \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo                                                   \
        "$@"
}
