#! /bin/sh

name=autoconf
from_source=autoconf
revision=1

configure() {
    "${source_dir}/configure" --prefix="${prefix}"
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install
}
