#! /bin/sh

name=binutils
from_source=binutils
revision=1
imagedeps="build-essential"

configure() {
    "${source_dir}"/configure               \
            --prefix="${prefix}"            \
            --target="${TRIPLE}"            \
            --with-sysroot="${sysroot_dir}" \
            --disable-nls
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install
}
