#! /bin/sh

name=pkg-config
from_source=pkg-config
revision=1
imagedeps="build-essential"

configure() {
    "${source_dir}"/configure               \
            --prefix="${prefix}"
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install
    mkdir -p "${dest_dir}${prefix}/share/pkgconfig/personality.d"
    cat > "${dest_dir}${prefix}/share/pkgconfig/personality.d/${TRIPLE}.personality" << EOF
Triplet: ${TRIPLE}
SysrootDir: ${sysroot_dir}
DefaultSearchPaths: ${sysroot_dir}/usr/lib/pkgconfig:${sysroot_dir}/usr/share/pkgconfig
SystemIncludePaths: ${sysroot_dir}/usr/include
SystemLibraryPaths: ${sysroot_dir}/usr/lib
EOF
    ln -s pkgconf "${dest_dir}${prefix}/bin/${TRIPLE}-pkg-config"
}
